archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
before:
  hooks:
    - 'go mod download'
builds:
  - binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    main: ./cmd/vault-plugin-harbor/main.go
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
