name: Unit Test
on:
  push:
    tags:
      - v*
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - run: make init
      - run: make fmt
      - run: make staticcheck
      - run: make test
