name: Trivy scanning
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scanners: 'vuln'
          vuln-type: 'library'
          exit-code: 1
          format: 'sarif'
          output: 'trivy-results.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
